version: '2.4'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT_EXPOSE}:5432
    healthcheck:
      test: /var/run/app/pg_healthcheck.sh
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - database:/var/lib/mysql:rw
      - ${PWD}/scripts:/var/run/app:rw

volumes:
  database:
    driver: local
